name: Solana-lto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rust update
      run: rustup update
    - name: sudo apt-get update
      run: sudo apt-get update
    - name: sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make
      run: sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make
    - name: Create Cargo.toml file
      run: |
         mkdir -p /home/runner/work/solana-1.9.4/solana-1.9.4/log-analyzer
         chmod +x /home/runner/work/solana-1.9.4/solana-1.9.4
         chmod +x /home/runner/work/solana-1.9.4/solana-1.9.4/log-analyzer
         touch /home/runner/work/solana-1.9.4/solana-1.9.4/log-analyzer/Cargo.toml
    - name: Add profile release
      run: echo [profile.release] >> Cargo.toml
    - name: Add lto = true
      run: echo lto = true >> Cargo.toml
    - name: cat cargo.toml
      run: cat Cargo.toml
    - name: cp cargo.toml
      run: cp Cargo.toml /home/runner/work/solana-1.9.4/solana-1.9.4/log-analyzer/Cargo.toml
    - name: Build
      run:  | 
         
         chmod +x /home/runner/work/solana-1.9.4/solana-1.9.4/cargo
         chmod +x ./scripts/cargo-install-all.sh 
         ./scripts/cargo-install-all.sh .
      shell: bash
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artifacts
        path: .
    
